//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("applicationModel", "FK_Role_Features_0", "lkup_Features", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.lkup_Features), "Role_Features", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.Role_Features), true)]
[assembly: EdmRelationshipAttribute("applicationModel", "FK_Role_Features_1", "lkup_Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.lkup_Roles), "Role_Features", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.Role_Features), true)]
[assembly: EdmRelationshipAttribute("applicationModel", "FK_Users_0", "lkup_Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.lkup_Roles), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.User), true)]
[assembly: EdmRelationshipAttribute("applicationModel", "FK_Users_01", "Palinoia_Projects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.Palinoia_Projects), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.User), true)]
[assembly: EdmRelationshipAttribute("applicationModel", "FK_Application_Errors_0", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.User), "Application_Errors", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.Application_Errors), true)]
[assembly: EdmRelationshipAttribute("applicationModel", "FK_Application_Errors_1", "Palinoia_Projects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.Palinoia_Projects), "Application_Errors", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.Application_Errors), true)]

#endregion

namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class applicationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new applicationEntities object using the connection string found in the 'applicationEntities' section of the application configuration file.
        /// </summary>
        public applicationEntities() : base("name=applicationEntities", "applicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new applicationEntities object.
        /// </summary>
        public applicationEntities(string connectionString) : base(connectionString, "applicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new applicationEntities object.
        /// </summary>
        public applicationEntities(EntityConnection connection) : base(connection, "applicationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Palinoia_Projects> Palinoia_Projects
        {
            get
            {
                if ((_Palinoia_Projects == null))
                {
                    _Palinoia_Projects = base.CreateObjectSet<Palinoia_Projects>("Palinoia_Projects");
                }
                return _Palinoia_Projects;
            }
        }
        private ObjectSet<Palinoia_Projects> _Palinoia_Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lkup_Features> lkup_Features
        {
            get
            {
                if ((_lkup_Features == null))
                {
                    _lkup_Features = base.CreateObjectSet<lkup_Features>("lkup_Features");
                }
                return _lkup_Features;
            }
        }
        private ObjectSet<lkup_Features> _lkup_Features;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lkup_Roles> lkup_Roles
        {
            get
            {
                if ((_lkup_Roles == null))
                {
                    _lkup_Roles = base.CreateObjectSet<lkup_Roles>("lkup_Roles");
                }
                return _lkup_Roles;
            }
        }
        private ObjectSet<lkup_Roles> _lkup_Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role_Features> Role_Features
        {
            get
            {
                if ((_Role_Features == null))
                {
                    _Role_Features = base.CreateObjectSet<Role_Features>("Role_Features");
                }
                return _Role_Features;
            }
        }
        private ObjectSet<Role_Features> _Role_Features;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Application_Errors> Application_Errors
        {
            get
            {
                if ((_Application_Errors == null))
                {
                    _Application_Errors = base.CreateObjectSet<Application_Errors>("Application_Errors");
                }
                return _Application_Errors;
            }
        }
        private ObjectSet<Application_Errors> _Application_Errors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Application_History> Application_History
        {
            get
            {
                if ((_Application_History == null))
                {
                    _Application_History = base.CreateObjectSet<Application_History>("Application_History");
                }
                return _Application_History;
            }
        }
        private ObjectSet<Application_History> _Application_History;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lkup_ApplicationFields> lkup_ApplicationFields
        {
            get
            {
                if ((_lkup_ApplicationFields == null))
                {
                    _lkup_ApplicationFields = base.CreateObjectSet<lkup_ApplicationFields>("lkup_ApplicationFields");
                }
                return _lkup_ApplicationFields;
            }
        }
        private ObjectSet<lkup_ApplicationFields> _lkup_ApplicationFields;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lkup_ApplicationObjects> lkup_ApplicationObjects
        {
            get
            {
                if ((_lkup_ApplicationObjects == null))
                {
                    _lkup_ApplicationObjects = base.CreateObjectSet<lkup_ApplicationObjects>("lkup_ApplicationObjects");
                }
                return _lkup_ApplicationObjects;
            }
        }
        private ObjectSet<lkup_ApplicationObjects> _lkup_ApplicationObjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Navigation_Menu_Items> Navigation_Menu_Items
        {
            get
            {
                if ((_Navigation_Menu_Items == null))
                {
                    _Navigation_Menu_Items = base.CreateObjectSet<Navigation_Menu_Items>("Navigation_Menu_Items");
                }
                return _Navigation_Menu_Items;
            }
        }
        private ObjectSet<Navigation_Menu_Items> _Navigation_Menu_Items;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Palinoia_Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPalinoia_Projects(Palinoia_Projects palinoia_Projects)
        {
            base.AddObject("Palinoia_Projects", palinoia_Projects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lkup_Features EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolkup_Features(lkup_Features lkup_Features)
        {
            base.AddObject("lkup_Features", lkup_Features);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lkup_Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolkup_Roles(lkup_Roles lkup_Roles)
        {
            base.AddObject("lkup_Roles", lkup_Roles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Role_Features EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRole_Features(Role_Features role_Features)
        {
            base.AddObject("Role_Features", role_Features);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Application_Errors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplication_Errors(Application_Errors application_Errors)
        {
            base.AddObject("Application_Errors", application_Errors);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Application_History EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplication_History(Application_History application_History)
        {
            base.AddObject("Application_History", application_History);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lkup_ApplicationFields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolkup_ApplicationFields(lkup_ApplicationFields lkup_ApplicationFields)
        {
            base.AddObject("lkup_ApplicationFields", lkup_ApplicationFields);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lkup_ApplicationObjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolkup_ApplicationObjects(lkup_ApplicationObjects lkup_ApplicationObjects)
        {
            base.AddObject("lkup_ApplicationObjects", lkup_ApplicationObjects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Navigation_Menu_Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNavigation_Menu_Items(Navigation_Menu_Items navigation_Menu_Items)
        {
            base.AddObject("Navigation_Menu_Items", navigation_Menu_Items);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="Application_Errors")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Application_Errors : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Application_Errors object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fk_UserID">Initial value of the fk_UserID property.</param>
        /// <param name="fk_ProjectID">Initial value of the fk_ProjectID property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static Application_Errors CreateApplication_Errors(global::System.Int64 id, global::System.Int64 fk_UserID, global::System.Int64 fk_ProjectID, global::System.DateTime date, global::System.Boolean active)
        {
            Application_Errors application_Errors = new Application_Errors();
            application_Errors.ID = id;
            application_Errors.fk_UserID = fk_UserID;
            application_Errors.fk_ProjectID = fk_ProjectID;
            application_Errors.Date = date;
            application_Errors.Active = active;
            return application_Errors;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_UserID
        {
            get
            {
                return _fk_UserID;
            }
            set
            {
                Onfk_UserIDChanging(value);
                ReportPropertyChanging("fk_UserID");
                _fk_UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_UserID");
                Onfk_UserIDChanged();
            }
        }
        private global::System.Int64 _fk_UserID;
        partial void Onfk_UserIDChanging(global::System.Int64 value);
        partial void Onfk_UserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_ProjectID
        {
            get
            {
                return _fk_ProjectID;
            }
            set
            {
                Onfk_ProjectIDChanging(value);
                ReportPropertyChanging("fk_ProjectID");
                _fk_ProjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_ProjectID");
                Onfk_ProjectIDChanged();
            }
        }
        private global::System.Int64 _fk_ProjectID;
        partial void Onfk_ProjectIDChanging(global::System.Int64 value);
        partial void Onfk_ProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InnerException
        {
            get
            {
                return _InnerException;
            }
            set
            {
                OnInnerExceptionChanging(value);
                ReportPropertyChanging("InnerException");
                _InnerException = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InnerException");
                OnInnerExceptionChanged();
            }
        }
        private global::System.String _InnerException;
        partial void OnInnerExceptionChanging(global::System.String value);
        partial void OnInnerExceptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StackTrace
        {
            get
            {
                return _StackTrace;
            }
            set
            {
                OnStackTraceChanging(value);
                ReportPropertyChanging("StackTrace");
                _StackTrace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StackTrace");
                OnStackTraceChanged();
            }
        }
        private global::System.String _StackTrace;
        partial void OnStackTraceChanging(global::System.String value);
        partial void OnStackTraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Application_Errors_0", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("applicationModel.FK_Application_Errors_0", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("applicationModel.FK_Application_Errors_0", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("applicationModel.FK_Application_Errors_0", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("applicationModel.FK_Application_Errors_0", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Application_Errors_1", "Palinoia_Projects")]
        public Palinoia_Projects Palinoia_Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palinoia_Projects>("applicationModel.FK_Application_Errors_1", "Palinoia_Projects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palinoia_Projects>("applicationModel.FK_Application_Errors_1", "Palinoia_Projects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Palinoia_Projects> Palinoia_ProjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palinoia_Projects>("applicationModel.FK_Application_Errors_1", "Palinoia_Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Palinoia_Projects>("applicationModel.FK_Application_Errors_1", "Palinoia_Projects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="Application_History")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Application_History : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Application_History object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Application_History CreateApplication_History(global::System.Int64 id)
        {
            Application_History application_History = new Application_History();
            application_History.ID = id;
            return application_History;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RecordID
        {
            get
            {
                return _RecordID;
            }
            set
            {
                OnRecordIDChanging(value);
                ReportPropertyChanging("RecordID");
                _RecordID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordID");
                OnRecordIDChanged();
            }
        }
        private Nullable<global::System.Int64> _RecordID;
        partial void OnRecordIDChanging(Nullable<global::System.Int64> value);
        partial void OnRecordIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OldValue
        {
            get
            {
                return _OldValue;
            }
            set
            {
                OnOldValueChanging(value);
                ReportPropertyChanging("OldValue");
                _OldValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OldValue");
                OnOldValueChanged();
            }
        }
        private global::System.String _OldValue;
        partial void OnOldValueChanging(global::System.String value);
        partial void OnOldValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewValue
        {
            get
            {
                return _NewValue;
            }
            set
            {
                OnNewValueChanging(value);
                ReportPropertyChanging("NewValue");
                _NewValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewValue");
                OnNewValueChanged();
            }
        }
        private global::System.String _NewValue;
        partial void OnNewValueChanging(global::System.String value);
        partial void OnNewValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UserID_UpdatedBy
        {
            get
            {
                return _UserID_UpdatedBy;
            }
            set
            {
                OnUserID_UpdatedByChanging(value);
                ReportPropertyChanging("UserID_UpdatedBy");
                _UserID_UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID_UpdatedBy");
                OnUserID_UpdatedByChanged();
            }
        }
        private Nullable<global::System.Int64> _UserID_UpdatedBy;
        partial void OnUserID_UpdatedByChanging(Nullable<global::System.Int64> value);
        partial void OnUserID_UpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> fk_ApplicationObjectID
        {
            get
            {
                return _fk_ApplicationObjectID;
            }
            set
            {
                Onfk_ApplicationObjectIDChanging(value);
                ReportPropertyChanging("fk_ApplicationObjectID");
                _fk_ApplicationObjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_ApplicationObjectID");
                Onfk_ApplicationObjectIDChanged();
            }
        }
        private Nullable<global::System.Int64> _fk_ApplicationObjectID;
        partial void Onfk_ApplicationObjectIDChanging(Nullable<global::System.Int64> value);
        partial void Onfk_ApplicationObjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> fk_ApplicationFieldID
        {
            get
            {
                return _fk_ApplicationFieldID;
            }
            set
            {
                Onfk_ApplicationFieldIDChanging(value);
                ReportPropertyChanging("fk_ApplicationFieldID");
                _fk_ApplicationFieldID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_ApplicationFieldID");
                Onfk_ApplicationFieldIDChanged();
            }
        }
        private Nullable<global::System.Int64> _fk_ApplicationFieldID;
        partial void Onfk_ApplicationFieldIDChanging(Nullable<global::System.Int64> value);
        partial void Onfk_ApplicationFieldIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="lkup_ApplicationFields")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lkup_ApplicationFields : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lkup_ApplicationFields object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Text property.</param>
        public static lkup_ApplicationFields Createlkup_ApplicationFields(global::System.Int64 id, global::System.String name)
        {
            lkup_ApplicationFields lkup_ApplicationFields = new lkup_ApplicationFields();
            lkup_ApplicationFields.ID = id;
            lkup_ApplicationFields.Name = name;
            return lkup_ApplicationFields;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="lkup_ApplicationObjects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lkup_ApplicationObjects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lkup_ApplicationObjects object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tEXT">Initial value of the TEXT property.</param>
        public static lkup_ApplicationObjects Createlkup_ApplicationObjects(global::System.Int64 id, global::System.String tEXT)
        {
            lkup_ApplicationObjects lkup_ApplicationObjects = new lkup_ApplicationObjects();
            lkup_ApplicationObjects.ID = id;
            lkup_ApplicationObjects.TEXT = tEXT;
            return lkup_ApplicationObjects;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEXT
        {
            get
            {
                return _TEXT;
            }
            set
            {
                OnTEXTChanging(value);
                ReportPropertyChanging("TEXT");
                _TEXT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TEXT");
                OnTEXTChanged();
            }
        }
        private global::System.String _TEXT;
        partial void OnTEXTChanging(global::System.String value);
        partial void OnTEXTChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="lkup_Features")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lkup_Features : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lkup_Features object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        public static lkup_Features Createlkup_Features(global::System.Int64 id, global::System.String text, global::System.Boolean active, global::System.Int64 updatedBy)
        {
            lkup_Features lkup_Features = new lkup_Features();
            lkup_Features.ID = id;
            lkup_Features.Text = text;
            lkup_Features.Active = active;
            lkup_Features.UpdatedBy = updatedBy;
            return lkup_Features;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.Int64 _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.Int64 value);
        partial void OnUpdatedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Role_Features_0", "Role_Features")]
        public EntityCollection<Role_Features> Role_Features
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Role_Features>("applicationModel.FK_Role_Features_0", "Role_Features");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Role_Features>("applicationModel.FK_Role_Features_0", "Role_Features", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="lkup_Roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lkup_Roles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lkup_Roles object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        public static lkup_Roles Createlkup_Roles(global::System.Int64 id, global::System.String text, global::System.Boolean active, global::System.Int64 updatedBy)
        {
            lkup_Roles lkup_Roles = new lkup_Roles();
            lkup_Roles.ID = id;
            lkup_Roles.Text = text;
            lkup_Roles.Active = active;
            lkup_Roles.UpdatedBy = updatedBy;
            return lkup_Roles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.Int64 _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.Int64 value);
        partial void OnUpdatedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Role_Features_1", "Role_Features")]
        public EntityCollection<Role_Features> Role_Features
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Role_Features>("applicationModel.FK_Role_Features_1", "Role_Features");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Role_Features>("applicationModel.FK_Role_Features_1", "Role_Features", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Users_0", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("applicationModel.FK_Users_0", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("applicationModel.FK_Users_0", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="Navigation_Menu_Items")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Navigation_Menu_Items : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Navigation_Menu_Items object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Navigation_Menu_Items CreateNavigation_Menu_Items(global::System.Int64 id)
        {
            Navigation_Menu_Items navigation_Menu_Items = new Navigation_Menu_Items();
            navigation_Menu_Items.ID = id;
            return navigation_Menu_Items;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Int64> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NodeID
        {
            get
            {
                return _NodeID;
            }
            set
            {
                OnNodeIDChanging(value);
                ReportPropertyChanging("NodeID");
                _NodeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NodeID");
                OnNodeIDChanged();
            }
        }
        private global::System.String _NodeID;
        partial void OnNodeIDChanging(global::System.String value);
        partial void OnNodeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FeatureID
        {
            get
            {
                return _FeatureID;
            }
            set
            {
                OnFeatureIDChanging(value);
                ReportPropertyChanging("FeatureID");
                _FeatureID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeatureID");
                OnFeatureIDChanged();
            }
        }
        private Nullable<global::System.Int64> _FeatureID;
        partial void OnFeatureIDChanging(Nullable<global::System.Int64> value);
        partial void OnFeatureIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="Palinoia_Projects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Palinoia_Projects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Palinoia_Projects object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        /// <param name="dataSource">Initial value of the DataSource property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        public static Palinoia_Projects CreatePalinoia_Projects(global::System.Int64 id, global::System.String nAME, global::System.String dataSource, global::System.Boolean active, global::System.Int64 updatedBy)
        {
            Palinoia_Projects palinoia_Projects = new Palinoia_Projects();
            palinoia_Projects.ID = id;
            palinoia_Projects.NAME = nAME;
            palinoia_Projects.DataSource = dataSource;
            palinoia_Projects.Active = active;
            palinoia_Projects.UpdatedBy = updatedBy;
            return palinoia_Projects;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataSource
        {
            get
            {
                return _DataSource;
            }
            set
            {
                OnDataSourceChanging(value);
                ReportPropertyChanging("DataSource");
                _DataSource = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DataSource");
                OnDataSourceChanged();
            }
        }
        private global::System.String _DataSource;
        partial void OnDataSourceChanging(global::System.String value);
        partial void OnDataSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.Int64 _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.Int64 value);
        partial void OnUpdatedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Users_01", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("applicationModel.FK_Users_01", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("applicationModel.FK_Users_01", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Application_Errors_1", "Application_Errors")]
        public EntityCollection<Application_Errors> Application_Errors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Application_Errors>("applicationModel.FK_Application_Errors_1", "Application_Errors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Application_Errors>("applicationModel.FK_Application_Errors_1", "Application_Errors", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="Role_Features")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role_Features : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role_Features object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fk_RoleID">Initial value of the fk_RoleID property.</param>
        /// <param name="fk_FeatureID">Initial value of the fk_FeatureID property.</param>
        public static Role_Features CreateRole_Features(global::System.Int64 id, global::System.Int64 fk_RoleID, global::System.Int64 fk_FeatureID)
        {
            Role_Features role_Features = new Role_Features();
            role_Features.ID = id;
            role_Features.fk_RoleID = fk_RoleID;
            role_Features.fk_FeatureID = fk_FeatureID;
            return role_Features;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_RoleID
        {
            get
            {
                return _fk_RoleID;
            }
            set
            {
                Onfk_RoleIDChanging(value);
                ReportPropertyChanging("fk_RoleID");
                _fk_RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_RoleID");
                Onfk_RoleIDChanged();
            }
        }
        private global::System.Int64 _fk_RoleID;
        partial void Onfk_RoleIDChanging(global::System.Int64 value);
        partial void Onfk_RoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_FeatureID
        {
            get
            {
                return _fk_FeatureID;
            }
            set
            {
                Onfk_FeatureIDChanging(value);
                ReportPropertyChanging("fk_FeatureID");
                _fk_FeatureID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_FeatureID");
                Onfk_FeatureIDChanged();
            }
        }
        private global::System.Int64 _fk_FeatureID;
        partial void Onfk_FeatureIDChanging(global::System.Int64 value);
        partial void Onfk_FeatureIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Role_Features_0", "lkup_Features")]
        public lkup_Features lkup_Features
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Features>("applicationModel.FK_Role_Features_0", "lkup_Features").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Features>("applicationModel.FK_Role_Features_0", "lkup_Features").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lkup_Features> lkup_FeaturesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Features>("applicationModel.FK_Role_Features_0", "lkup_Features");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lkup_Features>("applicationModel.FK_Role_Features_0", "lkup_Features", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Role_Features_1", "lkup_Roles")]
        public lkup_Roles lkup_Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Roles>("applicationModel.FK_Role_Features_1", "lkup_Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Roles>("applicationModel.FK_Role_Features_1", "lkup_Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lkup_Roles> lkup_RolesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Roles>("applicationModel.FK_Role_Features_1", "lkup_Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lkup_Roles>("applicationModel.FK_Role_Features_1", "lkup_Roles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="applicationModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fk_UserRoleID">Initial value of the fk_UserRoleID property.</param>
        /// <param name="pW">Initial value of the PW property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="fk_ProjectID">Initial value of the fk_ProjectID property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        public static User CreateUser(global::System.Int64 id, global::System.Int64 fk_UserRoleID, global::System.String pW, global::System.Boolean active, global::System.Int64 fk_ProjectID, global::System.Int64 updatedBy)
        {
            User user = new User();
            user.ID = id;
            user.fk_UserRoleID = fk_UserRoleID;
            user.PW = pW;
            user.Active = active;
            user.fk_ProjectID = fk_ProjectID;
            user.UpdatedBy = updatedBy;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_UserRoleID
        {
            get
            {
                return _fk_UserRoleID;
            }
            set
            {
                Onfk_UserRoleIDChanging(value);
                ReportPropertyChanging("fk_UserRoleID");
                _fk_UserRoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_UserRoleID");
                Onfk_UserRoleIDChanged();
            }
        }
        private global::System.Int64 _fk_UserRoleID;
        partial void Onfk_UserRoleIDChanging(global::System.Int64 value);
        partial void Onfk_UserRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleInitial
        {
            get
            {
                return _MiddleInitial;
            }
            set
            {
                OnMiddleInitialChanging(value);
                ReportPropertyChanging("MiddleInitial");
                _MiddleInitial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleInitial");
                OnMiddleInitialChanged();
            }
        }
        private global::System.String _MiddleInitial;
        partial void OnMiddleInitialChanging(global::System.String value);
        partial void OnMiddleInitialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PW
        {
            get
            {
                return _PW;
            }
            set
            {
                OnPWChanging(value);
                ReportPropertyChanging("PW");
                _PW = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PW");
                OnPWChanged();
            }
        }
        private global::System.String _PW;
        partial void OnPWChanging(global::System.String value);
        partial void OnPWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 fk_ProjectID
        {
            get
            {
                return _fk_ProjectID;
            }
            set
            {
                Onfk_ProjectIDChanging(value);
                ReportPropertyChanging("fk_ProjectID");
                _fk_ProjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fk_ProjectID");
                Onfk_ProjectIDChanged();
            }
        }
        private global::System.Int64 _fk_ProjectID;
        partial void Onfk_ProjectIDChanging(global::System.Int64 value);
        partial void Onfk_ProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.Int64 _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.Int64 value);
        partial void OnUpdatedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Users_0", "lkup_Roles")]
        public lkup_Roles lkup_Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Roles>("applicationModel.FK_Users_0", "lkup_Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Roles>("applicationModel.FK_Users_0", "lkup_Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lkup_Roles> lkup_RolesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Roles>("applicationModel.FK_Users_0", "lkup_Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lkup_Roles>("applicationModel.FK_Users_0", "lkup_Roles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Users_01", "Palinoia_Projects")]
        public Palinoia_Projects Palinoia_Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palinoia_Projects>("applicationModel.FK_Users_01", "Palinoia_Projects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palinoia_Projects>("applicationModel.FK_Users_01", "Palinoia_Projects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Palinoia_Projects> Palinoia_ProjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Palinoia_Projects>("applicationModel.FK_Users_01", "Palinoia_Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Palinoia_Projects>("applicationModel.FK_Users_01", "Palinoia_Projects", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("applicationModel", "FK_Application_Errors_0", "Application_Errors")]
        public EntityCollection<Application_Errors> Application_Errors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Application_Errors>("applicationModel.FK_Application_Errors_0", "Application_Errors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Application_Errors>("applicationModel.FK_Application_Errors_0", "Application_Errors", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
