//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("palinoiaModel", "FK_BusinessRules_0", "lkup_Status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Palinoia.lkup_Status), "BusinessRules", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Palinoia.BusinessRule), true)]
[assembly: EdmRelationshipAttribute("palinoiaModel", "FK_CustomerServiceMessages_0", "lkup_CSMResponseType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Palinoia.lkup_CSMResponseType), "CustomerServiceMessages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Palinoia.CustomerServiceMessage), true)]
[assembly: EdmRelationshipAttribute("palinoiaModel", "FK_CustomerServiceMessages_1", "lkup_CMSType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Palinoia.lkup_CMSType), "CustomerServiceMessages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Palinoia.CustomerServiceMessage), true)]
[assembly: EdmRelationshipAttribute("palinoiaModel", "FK_CustomerServiceMessages_2", "lkup_Status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Palinoia.lkup_Status), "CustomerServiceMessages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Palinoia.CustomerServiceMessage), true)]

#endregion

namespace Palinoia
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class palinoiaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new palinoiaEntities object using the connection string found in the 'palinoiaEntities' section of the application configuration file.
        /// </summary>
        public palinoiaEntities() : base("name=palinoiaEntities", "palinoiaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new palinoiaEntities object.
        /// </summary>
        public palinoiaEntities(string connectionString) : base(connectionString, "palinoiaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new palinoiaEntities object.
        /// </summary>
        public palinoiaEntities(EntityConnection connection) : base(connection, "palinoiaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BusinessRule> BusinessRules
        {
            get
            {
                if ((_BusinessRules == null))
                {
                    _BusinessRules = base.CreateObjectSet<BusinessRule>("BusinessRules");
                }
                return _BusinessRules;
            }
        }
        private ObjectSet<BusinessRule> _BusinessRules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerServiceMessage> CustomerServiceMessages
        {
            get
            {
                if ((_CustomerServiceMessages == null))
                {
                    _CustomerServiceMessages = base.CreateObjectSet<CustomerServiceMessage>("CustomerServiceMessages");
                }
                return _CustomerServiceMessages;
            }
        }
        private ObjectSet<CustomerServiceMessage> _CustomerServiceMessages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lkup_CMSType> lkup_CMSType
        {
            get
            {
                if ((_lkup_CMSType == null))
                {
                    _lkup_CMSType = base.CreateObjectSet<lkup_CMSType>("lkup_CMSType");
                }
                return _lkup_CMSType;
            }
        }
        private ObjectSet<lkup_CMSType> _lkup_CMSType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lkup_CSMResponseType> lkup_CSMResponseType
        {
            get
            {
                if ((_lkup_CSMResponseType == null))
                {
                    _lkup_CSMResponseType = base.CreateObjectSet<lkup_CSMResponseType>("lkup_CSMResponseType");
                }
                return _lkup_CSMResponseType;
            }
        }
        private ObjectSet<lkup_CSMResponseType> _lkup_CSMResponseType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lkup_Status> lkup_Status
        {
            get
            {
                if ((_lkup_Status == null))
                {
                    _lkup_Status = base.CreateObjectSet<lkup_Status>("lkup_Status");
                }
                return _lkup_Status;
            }
        }
        private ObjectSet<lkup_Status> _lkup_Status;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BusinessRules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBusinessRules(BusinessRule businessRule)
        {
            base.AddObject("BusinessRules", businessRule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerServiceMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerServiceMessages(CustomerServiceMessage customerServiceMessage)
        {
            base.AddObject("CustomerServiceMessages", customerServiceMessage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lkup_CMSType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolkup_CMSType(lkup_CMSType lkup_CMSType)
        {
            base.AddObject("lkup_CMSType", lkup_CMSType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lkup_CSMResponseType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolkup_CSMResponseType(lkup_CSMResponseType lkup_CSMResponseType)
        {
            base.AddObject("lkup_CSMResponseType", lkup_CSMResponseType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lkup_Status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolkup_Status(lkup_Status lkup_Status)
        {
            base.AddObject("lkup_Status", lkup_Status);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="palinoiaModel", Name="BusinessRule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BusinessRule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BusinessRule object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="statusID">Initial value of the StatusID property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static BusinessRule CreateBusinessRule(global::System.Int64 id, global::System.String name, global::System.Int64 statusID, global::System.String text)
        {
            BusinessRule businessRule = new BusinessRule();
            businessRule.ID = id;
            businessRule.Name = name;
            businessRule.StatusID = statusID;
            businessRule.Text = text;
            return businessRule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 StatusID
        {
            get
            {
                return _StatusID;
            }
            set
            {
                OnStatusIDChanging(value);
                ReportPropertyChanging("StatusID");
                _StatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusID");
                OnStatusIDChanged();
            }
        }
        private global::System.Int64 _StatusID;
        partial void OnStatusIDChanging(global::System.Int64 value);
        partial void OnStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_BusinessRules_0", "lkup_Status")]
        public lkup_Status lkup_Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Status>("palinoiaModel.FK_BusinessRules_0", "lkup_Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Status>("palinoiaModel.FK_BusinessRules_0", "lkup_Status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lkup_Status> lkup_StatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Status>("palinoiaModel.FK_BusinessRules_0", "lkup_Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lkup_Status>("palinoiaModel.FK_BusinessRules_0", "lkup_Status", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="palinoiaModel", Name="CustomerServiceMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerServiceMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerServiceMessage object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="statusID">Initial value of the StatusID property.</param>
        /// <param name="typeID">Initial value of the TypeID property.</param>
        /// <param name="responseID">Initial value of the ResponseID property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static CustomerServiceMessage CreateCustomerServiceMessage(global::System.Int64 id, global::System.String name, global::System.Int64 statusID, global::System.Int64 typeID, global::System.Int64 responseID, global::System.String text)
        {
            CustomerServiceMessage customerServiceMessage = new CustomerServiceMessage();
            customerServiceMessage.ID = id;
            customerServiceMessage.Name = name;
            customerServiceMessage.StatusID = statusID;
            customerServiceMessage.TypeID = typeID;
            customerServiceMessage.ResponseID = responseID;
            customerServiceMessage.Text = text;
            return customerServiceMessage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 StatusID
        {
            get
            {
                return _StatusID;
            }
            set
            {
                OnStatusIDChanging(value);
                ReportPropertyChanging("StatusID");
                _StatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusID");
                OnStatusIDChanged();
            }
        }
        private global::System.Int64 _StatusID;
        partial void OnStatusIDChanging(global::System.Int64 value);
        partial void OnStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TypeID
        {
            get
            {
                return _TypeID;
            }
            set
            {
                OnTypeIDChanging(value);
                ReportPropertyChanging("TypeID");
                _TypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeID");
                OnTypeIDChanged();
            }
        }
        private global::System.Int64 _TypeID;
        partial void OnTypeIDChanging(global::System.Int64 value);
        partial void OnTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ResponseID
        {
            get
            {
                return _ResponseID;
            }
            set
            {
                OnResponseIDChanging(value);
                ReportPropertyChanging("ResponseID");
                _ResponseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResponseID");
                OnResponseIDChanged();
            }
        }
        private global::System.Int64 _ResponseID;
        partial void OnResponseIDChanging(global::System.Int64 value);
        partial void OnResponseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_CustomerServiceMessages_0", "lkup_CSMResponseType")]
        public lkup_CSMResponseType lkup_CSMResponseType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_CSMResponseType>("palinoiaModel.FK_CustomerServiceMessages_0", "lkup_CSMResponseType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_CSMResponseType>("palinoiaModel.FK_CustomerServiceMessages_0", "lkup_CSMResponseType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lkup_CSMResponseType> lkup_CSMResponseTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_CSMResponseType>("palinoiaModel.FK_CustomerServiceMessages_0", "lkup_CSMResponseType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lkup_CSMResponseType>("palinoiaModel.FK_CustomerServiceMessages_0", "lkup_CSMResponseType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_CustomerServiceMessages_1", "lkup_CMSType")]
        public lkup_CMSType lkup_CMSType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_CMSType>("palinoiaModel.FK_CustomerServiceMessages_1", "lkup_CMSType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_CMSType>("palinoiaModel.FK_CustomerServiceMessages_1", "lkup_CMSType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lkup_CMSType> lkup_CMSTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_CMSType>("palinoiaModel.FK_CustomerServiceMessages_1", "lkup_CMSType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lkup_CMSType>("palinoiaModel.FK_CustomerServiceMessages_1", "lkup_CMSType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_CustomerServiceMessages_2", "lkup_Status")]
        public lkup_Status lkup_Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Status>("palinoiaModel.FK_CustomerServiceMessages_2", "lkup_Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Status>("palinoiaModel.FK_CustomerServiceMessages_2", "lkup_Status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lkup_Status> lkup_StatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lkup_Status>("palinoiaModel.FK_CustomerServiceMessages_2", "lkup_Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lkup_Status>("palinoiaModel.FK_CustomerServiceMessages_2", "lkup_Status", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="palinoiaModel", Name="lkup_CMSType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lkup_CMSType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lkup_CMSType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static lkup_CMSType Createlkup_CMSType(global::System.Int64 id, global::System.String text)
        {
            lkup_CMSType lkup_CMSType = new lkup_CMSType();
            lkup_CMSType.ID = id;
            lkup_CMSType.Text = text;
            return lkup_CMSType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_CustomerServiceMessages_1", "CustomerServiceMessages")]
        public EntityCollection<CustomerServiceMessage> CustomerServiceMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerServiceMessage>("palinoiaModel.FK_CustomerServiceMessages_1", "CustomerServiceMessages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerServiceMessage>("palinoiaModel.FK_CustomerServiceMessages_1", "CustomerServiceMessages", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="palinoiaModel", Name="lkup_CSMResponseType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lkup_CSMResponseType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lkup_CSMResponseType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static lkup_CSMResponseType Createlkup_CSMResponseType(global::System.Int64 id, global::System.String text)
        {
            lkup_CSMResponseType lkup_CSMResponseType = new lkup_CSMResponseType();
            lkup_CSMResponseType.ID = id;
            lkup_CSMResponseType.Text = text;
            return lkup_CSMResponseType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_CustomerServiceMessages_0", "CustomerServiceMessages")]
        public EntityCollection<CustomerServiceMessage> CustomerServiceMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerServiceMessage>("palinoiaModel.FK_CustomerServiceMessages_0", "CustomerServiceMessages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerServiceMessage>("palinoiaModel.FK_CustomerServiceMessages_0", "CustomerServiceMessages", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="palinoiaModel", Name="lkup_Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lkup_Status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lkup_Status object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static lkup_Status Createlkup_Status(global::System.Int64 id, global::System.String text)
        {
            lkup_Status lkup_Status = new lkup_Status();
            lkup_Status.ID = id;
            lkup_Status.Text = text;
            return lkup_Status;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_BusinessRules_0", "BusinessRules")]
        public EntityCollection<BusinessRule> BusinessRules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BusinessRule>("palinoiaModel.FK_BusinessRules_0", "BusinessRules");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BusinessRule>("palinoiaModel.FK_BusinessRules_0", "BusinessRules", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("palinoiaModel", "FK_CustomerServiceMessages_2", "CustomerServiceMessages")]
        public EntityCollection<CustomerServiceMessage> CustomerServiceMessages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerServiceMessage>("palinoiaModel.FK_CustomerServiceMessages_2", "CustomerServiceMessages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerServiceMessage>("palinoiaModel.FK_CustomerServiceMessages_2", "CustomerServiceMessages", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
